language: python
cache: pip
dist: xenial
python:
  - "3.6"
# command to install dependencies
before_install:
  - sudo apt-get install -y antlr4
install:
  - pip install --upgrade pip
  - pip install -r deepppl/requirements.txt --progress-bar off
  - pip install pystan==2.17.1.0 --progress-bar off
  - pip install scikit-learn==0.20.1 --progress-bar off

# command to run tests
before_script:
  - cd deepppl
  - make
  - cd ..
  - pip install .
script:
  - export PYTHONHASHSEED=0
  - pytest -v
