language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install --progress-bar off -r deepppl/requirements.txt
# command to run tests
script:
  - python dpplc.py tests/good/coin.stan # or py.test for Python versions 3.5 and below
